server:
  port: 8080

spring:
  main:
    banner-mode: off

  datasource:
    url: ${DATASOURCE.URL}
    username: ${DATASOURCE.USERNAME}
    password: ${DATASOURCE.PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changes/v0.0.1-SNAPSHOT/v0.0.1-master.xml

  jpa:
    properties:
      hibernate:
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true