server:
  port: 8080

spring:
  main:
    banner-mode: off
  datasource:
    url: ${DATASOURCE.URL}
    username: ${DATASOURCE.USERNAME}
    password: ${DATASOURCE.PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changes/v0.0.1-SNAPSHOT/v0.0.1-master.xml

  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.example.com
    username: user@example.com
    password: password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#
#jwt:
#  secret:
#    access: "CJUIR+3cQjBjaGM3tHzjFY5/VRyGbiVccrezNMUnM8M="
#    refresh: "Aw5EPKS75TnCgF9S5Bs7diIPmp065owR6yfCf3S2B00="
#  expirations: 432000000

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

#springdoc:
#  webjars:
#    prefix:
#  swagger-ui:
#    path: /api/swagger-ui.html
#    disable-swagger-default-url: true
#    enabled: true
#    operationsSorter: alpha
#    tagsSorter: alpha
#    doc-expansion: none
#  api-docs:
#    enabled: true
#    path: /api/api-docs


springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

#
#redis:
#  login: "admin"
#  password: "1595admin"
#  host: localhost
#  port: 6379

