spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/airticket
    username: root
    password: 49vobollo1403V

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
      change-log: classpath:db/changelog/charges/v0.0.1-SNAPSHOT/v0.0.1-master.xml
