server:
  port: 8080
  servlet:
    context-path: /
spring:
  main:
    banner-mode: off

  datasource:
    url: ${DATASOURCE.URL}
    username: ${DATASOURCE.USERNAME}
    password: ${DATASOURCE.PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/changes/v0.0.1-SNAPSHOT/v0.0.1-master.xml
