spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/airticket
    username: root
    password: 49vobollo1403V
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:/db/changelog/changes/v0.0.1-SNAPSHOT/v0.0.1-master.xml
