server:
  port: 8080

spring:
  main:
    banner-mode: off
  datasource:
    url: ${DATASOURCE.URL}
    username: ${DATASOURCE.USERNAME}
    password: ${DATASOURCE.PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changes/v0.0.1-SNAPSHOT/v0.0.1-master.xml

  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.example.com
    username: user@example.com
    password: password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

variables:
  jwtAccessSecret: "ZSuoWTLsAyYuvfLYso9dBn9yHKInkXwdO5SH690ovLg="
  jwtRefreshSecret: "refresh"
  jwtExpirationMS: 432000000

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

springdoc:
  api-docs:
    enabled: true
swagger-ui:
  enabled: true
